server:
  port: 9090
spring:
  rabbitmq:
    host: localhost
    username: portname
    password: 123
    port: 5672
  datasource:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Ornek
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true


rabbitmq:
  exchange-auth: ${rabbitmq-exchange-auth}
  bindingKey: ${rabbitmq-bindingKey}
  queueAcvitavted: ${rabbitmq-queueAcvitavted}
  userUpdateQueue: ${rabbitmq-userUpdateQueue}
