server:
  port: 9091
spring:
  rabbitmq:
    host: localhost
    username: portname
    password: 123
    port: 5672

#rabbitmq:
#  exchange-auth: ${rabbitmq-exchange-auth}
#  bindingKey: ${rabbitmq-bindingKey}
#  queueActivatedCode: ${rabbitmq-queueActivatedCode}
#  userUpdateQueue: ${rabbitmq-userUpdateQueue}
rabbitmq:
  exchange-auth: "exchange-auth"
  bindingKey: "bindingKey"
  queueActivatedCode: "queueActivatedCode"
  userUpdateQueue: "userUpdateQueue"
